export const userData = {
  data: [
    {
      id: 1844,
      name: "MoureDev",
      email: "mour@mail.com",
      gender: "male",
      status: "active",
    },
    {
      id: 1871,
      name: "Test name",
      email: "test-8801@email.ca",
      gender: "male",
      status: "inactive",
    },
    {
      id: 1873,
      name: "Test name",
      email: "test-6091@email.ca",
      gender: "male",
      status: "inactive",
    },
    {
      id: 1874,
      name: "Francielle Consoni8",
      email: "emailteste@gmail.com10",
      gender: "female",
      status: "active",
    },
    {
      id: 1875,
      name: "Ali",
      email: "ali3@gmail.com",
      gender: "male",
      status: "active",
    },
    {
      id: 1876,
      name: "Test name",
      email: "test-989@email.ca",
      gender: "male",
      status: "inactive",
    },
    {
      id: 1878,
      name: "Test name",
      email: "test-4543@email.ca",
      gender: "male",
      status: "inactive",
    },
    {
      id: 1883,
      name: "Sandesha Thandra",
      email: "newemail15@gmail.com",
      gender: "male",
      status: "active",
    },
    {
      id: 1885,
      name: "Tenali12345",
      email: "tenali12344@gmail.com",
      gender: "male",
      status: "active",
    },
    {
      id: 1886,
      name: "Sandesha Thandra",
      email: "newemail16@gmail.com",
      gender: "male",
      status: "active",
    },
    {
      id: 1890,
      name: "Sandesha Thandra",
      email: "newemail18@gmail.com",
      gender: "male",
      status: "active",
    },
    {
      id: 1891,
      name: "Tenali123456",
      email: "tenali123446@gmail.com",
      gender: "male",
      status: "active",
    },
    {
      id: 1893,
      name: "Sandesha Thandra",
      email: "newemail19@gmail.com",
      gender: "male",
      status: "active",
    },
    {
      id: 1895,
      name: "Sandesha Thandra",
      email: "newemail192132@gmail.com",
      gender: "male",
      status: "active",
    },
    {
      id: 1925,
      name: "dpradhan",
      email: "dipu38@gmail.com",
      gender: "male",
      status: "active",
    },
    {
      id: 1933,
      name: "Sandesha Thandra",
      email: "sandesha77566@gmail.com",
      gender: "female",
      status: "active",
    },
    {
      id: 1935,
      name: "yOoOo",
      email: "1230.7167912843076116@gmail.com",
      gender: "male",
      status: "active",
    },
    {
      id: 1937,
      name: "yOoOo",
      email: "1230.19089789058948958@gmail.com",
      gender: "male",
      status: "active",
    },
    {
      id: 1939,
      name: "grr",
      email: "1230.7900446226826063@gmail.com",
      gender: "male",
      status: "active",
    },
    {
      id: 1940,
      name: "yOoOo",
      email: "1230.7652627713538023@gmail.com",
      gender: "male",
      status: "active",
    },
  ],
};
